TebLocalPlannerROS:
  odom_topic: odom
  map_frame: map

  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1

  max_vel_x: 1.0
  max_vel_x_backwards: 0.5
  max_vel_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_theta: 1.0

  footprint_model:
    type: "polygon"
    vertices: [[0.35, 0.25], [0.35, -0.25], [-0.35, -0.25], [-0.35, 0.25]]

  min_obstacle_dist: 0.3
  inflation_dist: 0.5

  allow_init_with_backwards_motion: true
  global_plan_overwrite_orientation: true
  global_plan_viapoint_sep: 0.5
  enable_homotopy_class_planning: true
  max_number_classes: 4
